name: Build and deploy documentation

on:
  push:
    branches:
      - main
      - dev
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: SimeonEhrig/gh-actions/build-docs@supportCustomURLs
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-tools-url: https://github.com/SimeonEhrig/QED.jl.git
          github-tools-branch: refactorCustomDepURLs   
